version: "3.8"

services:
    # 1. Service Aplikasi (Laravel)
    app:
        build:
            context: .
            dockerfile: Dockerfile
        # Nama image yang akan dibangun
        image: absences-qr-app
        # Nama container saat berjalan
        container_name: absences-qr-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - absences-qr-network

    # 2. Service Web Server (Nginx)
    webserver:
        image: nginx:alpine
        container_name: absences-qr-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - absences-qr-network
        depends_on:
            - app

    # 3. Service Database (MySQL)
    db:
        image: mysql:8.0
        container_name: absences-qr-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - absences-qr-dbdata:/var/lib/mysql
        networks:
            - absences-qr-network

# Definisi Network dan Volume khusus proyek absences-qr
networks:
    absences-qr-network:
        driver: bridge

volumes:
    absences-qr-dbdata:
        driver: local
