version: 2

build:
  steps:
    - uses: actions/checkout@v3

  environment:
    PHP_VERSION: 8.2
    COMPOSER_VERSION: 2.x

deploy:
  # Perintah sebelum deployment
  pre_deploy:
    - composer install --optimize-autoloader --no-dev
    - php artisan config:clear
    - php artisan cache:clear
    - php artisan view:clear
    - php artisan route:cache
    - php artisan migrate --force

  # Konfigurasi environment
  environment:
    APP_ENV: production
    APP_DEBUG: false
    LOG_LEVEL: info
    DB_CONNECTION: mysql
    DB_HOST: mysql.railway.internal
    DB_PORT: 3306
    DB_DATABASE: railway
    DB_USERNAME: root
    DB_PASSWORD: aityIcGgbJzMPeTPASUAdpnIHigAugcQ

  # Konfigurasi server
  server:
    port: 8080
    host: 0.0.0.0

  # Migrasi database otomatis (opsional)
  database:
    auto_migrate: true
